#!/usr/bin/env bash
# A Bash script that stops the 4-to_infinity_and_beyond process

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "./4-to_infinity_and_beyond")

# Kill the process if it exists
if [ -n "$pid" ]; then
    kill "$pid"
fi
