#!/usr/bin/env bash
# A Bash script that kills the 7-highlander process using the SIGKILL signal (signal 9)

# Find the PID of the 7-highlander process
pid=$(pgrep -f "./7-highlander")

# Kill the process if it exists using SIGKILL (signal 9)
if [ -n "$pid" ]; then
    kill -9 "$pid"
fi
