#!/usr/bin/env bash
#This script displays the phrase "Best School" ten times and Hi on the 9th iteration using the while loop and if statement.

counter=0
while [ $counter -lt 10 ]; do
 echo "Best School"
 if [ $counter = 9 ]; then
  echo "Hi"
  fi
  counter=$((counter +1));
  done
