#!/usr/bin/env bash
#This script displays the phrase "Best School" ten times and Hi on the 9th iteration using the while loop and if statement.

counter=0
while [ $counter -lt 11 ]; do
if [ $counter = 10 ]; then
echo "Hi"
fi
 echo "Best School"
  counter=$((counter +1));
  done
