#!/usr/bin/env bash
#This script displays the phrase "Best School" ten times and displays Bad luck on the 4th line and good luck on the 8th line the while loop and if, elif and else statements.

counter=0
while [ $counter -lt 10 ]; do
 if [ $counter = 3 ]; then
 echo "bad luck"
elif [ $counter = 7 ]; then
   echo "good luck"
 else 
   echo "Best School"
   fi
 counter=$((counter + 1 )); 
done

